# Generated by Django 4.2 on 2023-04-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plain_password',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
