# Generated by Django 4.2 on 2023-04-05 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_post_slug_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='content',
            field=models.TextField(default='No content'),
        ),
        migrations.AddField(
            model_name='student',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
