# Generated by Django 4.2 on 2023-04-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_student_content_student_title_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='major',
            new_name='designation',
        ),
        migrations.AddField(
            model_name='student',
            name='collageinfo',
            field=models.TextField(default='No content'),
        ),
        migrations.AddField(
            model_name='student',
            name='designationinfo',
            field=models.TextField(default='No content'),
        ),
    ]
